version: '3.8'

services:
  frontend:
    build: ./bikeshop-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./bikeshop-frontend:/app
    depends_on:
      - backend

  backend:
    build: ./bikeshop-backend
    ports:
      - "5001:5000"
    volumes:
      - ./bikeshop-backend:/app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=bikeshop
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bikeshop
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
